### ISSUE TITLE
Does pyglet still need to be restricted?

### ISSUE THREAD

**Issue by hmaarrfk** [wkentaro/imgviz#22]
https://github.com/wkentaro/imgviz/blob/30ef8e16180b780984eb0d8d7c6d60a9d54137f5/setup.py#L90

Its webpage and pip say no.

**Comment by wkentaro** [comment]
This was because pyglet 1.5 won't support Python2.
But I think this is right time to drop Python2 support.

**Comment by wkentaro** [comment]
Closed via 68c81063ca7bdc45af4cf543e6bd0ac46c421e2b
