### ISSUE TITLE
Position deviation of boxes due to image padding

### ISSUE THREAD

**Issue by jshi31** [wkentaro/imgviz#28]
Hi, thanks for the convenient visualization tool. I just find a bug for drawing multiple boxes. 

The problem is caused by the image padding for out of boundary text, https://github.com/wkentaro/imgviz/blob/968ac5f9c0aaa5735e1230e7f241e5150da121bf/imgviz/draw.py#L342. When drawing multiple boxes sequentially, the first box has caption out of image boundary, then it will pad the image, then the image shape changes, which is incorrect to draw the second box.

**Comment by wkentaro** [comment]
Thanks for the report. https://github.com/wkentaro/imgviz/pull/29 should fix this issue.
