### ISSUE TITLE
Keys in pyglet_imshow are not handled correctly if numlock is enabled

### ISSUE THREAD

**Issue by streckus** [wkentaro/imgviz#30]
Hi, I think I found a bug in the pyglet_imshow module.

These checks seem to cause the on_key_press function to return without any output/action if numlock (modifiers = 16) or capslock (modifiers = 8) is enabled. Is this desired behaviour?
https://github.com/wkentaro/imgviz/blob/d6fc8490aada737599ff7d69f1191a085882afd1/imgviz/_io/_pyglet/pyglet_imshow.py#L72
https://github.com/wkentaro/imgviz/blob/d6fc8490aada737599ff7d69f1191a085882afd1/imgviz/_io/_pyglet/pyglet_imshow.py#L122
https://github.com/wkentaro/imgviz/blob/d6fc8490aada737599ff7d69f1191a085882afd1/imgviz/_io/_pyglet/pyglet_imshow.py#L157

**Comment by wkentaro** [comment]
That's expected, but I'm fine to change it since some people accidentally enable NumLock, which does not exist on my keyboard.

**Comment by streckus** [comment]
Maybe you could add some helpful output if the condition isn't met. On my machine NumLock was enabled by default and I had to debug into the code to find out why it wasn't working.

**Comment by wkentaro** [comment]
Removed the if block. Thanks for the feedback.
