### ISSUE TITLE
ModuleNotFoundError: No module named 'imgviz'

### ISSUE THREAD

**Issue by LLL-YUE** [wkentaro/imgviz#53]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/95279388/205048157-20ec082a-08e4-4add-afd8-0cdbcc20daee.png">
I have already downloaded imgviz, but I fail to import imgviz in python. What's wrong?

**Comment by wkentaro** [comment]
Closing for now, please report again if reproduced.
